version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    environment:
      TZ: "America/Los_Angeles"
      NODE_PATH: src/
      SASS_PATH: src/
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Test and Coverage
          command: npm test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build